# Generated by Django 2.1.5 on 2019-02-06 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_address', models.CharField(help_text='full_address_help_text', max_length=256, verbose_name='full_address_label')),
                ('main_address', models.BooleanField(default=False, help_text='main_address_help_text', verbose_name='main_address_label')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='year_help_text', verbose_name='year_label')),
                ('name', models.CharField(help_text='name_help_text', max_length=64, verbose_name='name_label')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='first_name_help_text', max_length=64, verbose_name='first_name_label')),
                ('last_name', models.CharField(help_text='last_name_help_text', max_length=64, verbose_name='last_name_label')),
                ('promotion', models.ForeignKey(help_text='promotion_help_text', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='myapp.Promotion', verbose_name='promotion_label')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='student',
            field=models.ForeignKey(help_text='first_name_help_text', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='myapp.Student', verbose_name='first_name_label'),
        ),
    ]
